name: lnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - dill
  - git>=2.22
  - h5py>=2.9.0
  - ignite>=0.2.0
  - jupyterlab>=0.35.5
  - matplotlib>=3.0.3
  - numpy>=1.16.3
  - pip>=19.1
  - python>=3.7.3
  - pytorch>=1.2.0
  - pyyaml>=5.1
  - scikit-image>=0.15.0
  - scikit-learn>=0.20.3
  - scipy>=1.2.1
  - tifffile>=0.15.1
  - torchvision>=0.2.1
  - z5py>=1.4.1
  - pip:
    - gputil>=1.4.0
    - pbs3>=3.0.2
