precision: &precision float
nnum: &nnum 19
z_out: &z_out 49

toolbox: # defines yaml placeholders
  scale: &scale 4
  interpol: &interpol 2
  lf_crop: &lf_crop [[0, null], [0, null], [0, null]]  # static
  ls_trf_crop: &ls_trf_crop [[0, null], [0, null], [8, -8], [8, -8]]  # static

  metrics: &metrics
    MSSSIM: {tensor_names: {y_pred: pred, y: ls_trf}, window_size: 11, size_average: true, val_range: null, normalize: false}
    SSIM: {tensor_names: {y_pred: pred, y: ls_trf}, window_size: 11, window: null, size_average: true, full: false, val_range: null}
    NRMSE: {tensor_names: {y_pred: pred, y: ls_trf}}
    PSNR: {tensor_names: {y_pred: pred, y: ls_trf}, data_range: null}
    SmoothL1Loss: {tensor_names: {y_pred: pred, y: ls_trf}}
    MSELoss: {tensor_names: {y_pred: pred, y: ls_trf}}

  eval_batch_size: &eval_batch_size 1
  sample_trfs: &sample_trfs []
  eval_sample_prepr: &eval_sample_prepr
    - Crop: {apply_to: lf, crop: *lf_crop}
    - Crop: {apply_to: ls_trf, crop: *ls_trf_crop}
    - Normalize01: {apply_to: lf, min_percentile: 5.0, max_percentile: 99.8}
    - Normalize01: {apply_to: ls_trf, min_percentile: 5.0, max_percentile: 99.99}
    - ChannelFromLightField: {apply_to: {lf: lfc}, nnum: *nnum}
  eval_batch_prepr: &eval_batch_prepr []
  batch_prepr_in_step: &batch_prepr_in_step
    - Cast: {apply_to: [lfc, ls_trf], dtype: *precision, device: cuda, non_blocking: true}
  batch_postpr: &batch_postpr
    - Assert: {apply_to: pred, expected_tensor_shape: [null, 1, *z_out, null, null]}

model:
  name: A04
  kwargs:
    scale: *scale
    input_name: lfc
    prediction_name: pred
    nnum: *nnum
    z_out: *z_out
    n_res2d: [488, 488, u, 244, 244]
#    n_res3d: [[7], [7], [7]]
  checkpoint:

stages:
  - train:
      max_epochs: 500
      metrics: {}
      log:
        save_n_checkpoints: 2
        TqdmLogger: {}
        TensorBoardLogger:
          scalars_every: {value: 10, unit: iteration}
          tensors_every: {value: 100, unit: iteration}
          tensor_names: [lf, pred, ls_trf]
        FileLogger:
          scalars_every: {value: 1, unit: epoch}
      criterion:
        name: MSELoss
        kwargs: {}
#         name: WeightedSmoothL1Loss
#         kwargs: {threshold: 1.0, initial_weight: .1, apply_below_threshold: true, decay_by: .8, every_nth_epoch: 1}
        tensor_names: {input: pred, target: ls_trf}

      optimizer:
        name: Adam
        kwargs: {lr: 1.0e-4, eps: 1.0e-8}

      sampler:
        base: RandomSampler
        drop_last: false

      batch_preprocessing:
        - RandomRotate90: {apply_to: [lf, ls_trf]}
        - ChannelFromLightField: {apply_to: {lf: lfc}, nnum: *nnum}
      batch_preprocessing_in_step: *batch_prepr_in_step
      batch_postprocessing: *batch_postpr

      data:
        - batch_size: 1
          interpolation_order: *interpol
          sample_transformations: *sample_trfs
          sample_preprocessing:
            - Crop: {apply_to: lf, crop: *lf_crop}
            - Crop: {apply_to: ls_trf, crop: *ls_trf_crop}
            - Normalize01: {apply_to: lf, min_percentile: 5.0, max_percentile: 99.8}
            - Normalize01: {apply_to: ls_trf, min_percentile: 5.0, max_percentile: 99.99}
            - AdditiveGaussianNoise: {apply_to: lf, sigma: 0.1}
            - AdditiveGaussianNoise: {apply_to: ls_trf, sigma: 0.05}
            - RandomIntensityScale: {apply_to: [lf, ls_trf], factor_min: .8, factor_max: 1.2}
            - RandomlyFlipAxis: {apply_to: [lf, ls_trf], axis: -1}
            - RandomlyFlipAxis: {apply_to: [lf, ls_trf], axis: -2}
          filters: []
          datasets:
            - {tensors: {lf: static_heart.2019-12-08_06.57.57, ls_trf: static_heart.2019-12-08_06.57.57, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.59.59, ls_trf: static_heart.2019-12-08_06.59.59, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_10.32.03, ls_trf: static_heart.2019-12-08_10.32.03, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.35.52, ls_trf: static_heart.2019-12-08_06.35.52, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.38.47, ls_trf: static_heart.2019-12-08_06.38.47, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.10.34, ls_trf: static_heart.2019-12-08_06.10.34, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.41.39, ls_trf: static_heart.2019-12-08_06.41.39, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.18.09, ls_trf: static_heart.2019-12-08_06.18.09, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.46.09, ls_trf: static_heart.2019-12-08_06.46.09, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.23.13, ls_trf: static_heart.2019-12-08_06.23.13, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.49.08, ls_trf: static_heart.2019-12-08_06.49.08, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.25.02, ls_trf: static_heart.2019-12-08_06.25.02, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.51.57, ls_trf: static_heart.2019-12-08_06.51.57, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.30.40, ls_trf: static_heart.2019-12-08_06.30.40, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_06.59.59, ls_trf: static_heart.2019-12-08_06.59.59, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-08_10.32.03, ls_trf: static_heart.2019-12-08_10.32.03, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_09.52.38, ls_trf: static_heart.2019-12-09_09.52.38, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_08.15.07, ls_trf: static_heart.2019-12-09_08.15.07, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_08.19.40, ls_trf: static_heart.2019-12-09_08.19.40, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_08.27.14, ls_trf: static_heart.2019-12-09_08.27.14, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.16.30, ls_trf: static_heart.2019-12-09_02.16.30, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.23.01, ls_trf: static_heart.2019-12-09_02.23.01, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.29.34, ls_trf: static_heart.2019-12-09_02.29.34, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.35.49, ls_trf: static_heart.2019-12-09_02.35.49, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.42.03, ls_trf: static_heart.2019-12-09_02.42.03, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.48.24, ls_trf: static_heart.2019-12-09_02.48.24, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
            - {tensors: {lf: static_heart.2019-12-09_02.54.46, ls_trf: static_heart.2019-12-09_02.54.46, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}

      validate:
        metrics: *metrics
        log:
          TqdmLogger: {}
          TensorBoardLogger:
            scalars_every: {value: 500, unit: iteration}
            tensors_every: {value: 500, unit: iteration}
            tensor_names: [lf, pred, ls_trf]
          FileLogger:
            scalars_every: {value: 500, unit: iteration}
        score_metric: MSSSIM
        period: {value: 500, unit: iteration}
        patience: 10
        batch_preprocessing: *eval_batch_prepr
        batch_preprocessing_in_step: *batch_prepr_in_step
        batch_postprocessing: *batch_postpr
        data:
          - batch_size: *eval_batch_size
            interpolation_order: *interpol
            sample_preprocessing: *eval_sample_prepr
            filters: []
            datasets:
              - {tensors: {lf: static_heart.2019-12-09_08.34.44, ls_trf: static_heart.2019-12-09_08.34.44, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
              - {tensors: {lf: static_heart.2019-12-09_08.41.41, ls_trf: static_heart.2019-12-09_08.41.41, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
              - {tensors: {lf: static_heart.2019-12-09_08.51.01, ls_trf: static_heart.2019-12-09_08.51.01, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
              - {tensors: {lf: static_heart.2019-12-09_09.01.28, ls_trf: static_heart.2019-12-09_09.01.28, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
              - {tensors: {lf: static_heart.2019-12-09_09.11.59, ls_trf: static_heart.2019-12-09_09.11.59, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
              - {tensors: {lf: static_heart.2019-12-09_09.18.01, ls_trf: static_heart.2019-12-09_09.18.01, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}

  - test:
      metrics: *metrics
      log:
        TqdmLogger: {}
        TensorBoardLogger:
          scalars_every: {value: 1, unit: epoch}
          tensors_every: {value: 1, unit: epoch}
        FileLogger:
          scalars_every: {value: 1, unit: epoch}
          tensors_every: {value: 1, unit: iteration}
          tensor_names: {lf, ls_trf, pred}
      batch_preprocessing: *eval_batch_prepr
      batch_preprocessing_in_step: *batch_prepr_in_step
      batch_postprocessing: *batch_postpr
      data:
        - batch_size: *eval_batch_size
          interpolation_order: *interpol
          sample_transformations: *sample_trfs
          sample_preprocessing: *eval_sample_prepr
          filters: []
          datasets:
            - {tensors: {lf: static_heart.2019-12-10_04.24.29, ls_trf: static_heart.2019-12-10_04.24.29, meta: {nnum: *nnum, z_out: *z_out, scale: *scale}}, indices: null}
