model:
  name: M12
  kwargs: {final_activation: sigmoid}
  nnum: 19
  precision: float
#  checkpoint: "/g/kreshuk/beuttenm/repos/lensletnet/logs/beads/00_LS0/8/19-09-19_14-28_db5e04e_8-0/models/v0_model_887.pth"

log:
    log_scalars_every: [10, iteration_completed]
    log_images_every: [10, epoch_completed]
    log_bead_precision_recall: true

train:
  loss_fn: WeightedL1Loss

  optimizer:
    name: Adam
    kwargs: {lr: 1.0e-4, eps: 1.0e-8}

  batch_size: 1
  max_num_epochs: 5000
  score_function: MS-SSIM
  patience: 30
  validate_every_nth_epoch: 10

eval:
  batch_size: 3

train_data:
  names: [regional_fish02_LS1, fish02_LS0_filet, bead00_LS0_35]
  indices: [5-73, null, 0-49]
  eval_indices: [5-8, 0-0, 0-3]
  transforms:
    - noise00
    - norm00
    - RandomRotate
    - RandomFlipXYnotZ
    - Lightfield2Channel

valid_data:
  names: [regional_fish02_LS1]
  indices: [4]
  transforms:
    - norm00
    - Lightfield2Channel

test_data:
  names: [regional_fish02_LS1]
  indices: [0-4]
  transforms:
    - norm00
    - Lightfield2Channel
