model:
  name: M12dout
  kwargs: {final_activation: sigmoid, aux_activation: null}
  nnum: 15
  precision: float

log:
    log_scalars_every: [10, iteration_completed]
    log_images_every: [10, epoch_completed]
    log_bead_precision_recall: true

train:
  loss:
    name: SorensenDiceLoss
  aux_loss:
    name: BCEWithLogitsLoss
  optimizer:
    name: Adam
    kwargs: {lr: 1.0e-4, eps: 1.0e-8}
  batch_size: 1
  max_num_epochs: 5000
  score_function: MS-SSIM
  patience: 30
  validate_every_nth_epoch: 10

eval:
  batch_size: 3

train_data:
  names: [platyn1]
  indices: [0-1300-130]
  eval_indices: [0]
  transforms:
    - noise00
    - norm00
    - RandomRotate
    - RandomFlipXYnotZ
    - Lightfield2Channel

valid_data:
  names: [platyn1]
  indices: [1312, 1319]
  transforms:
    - norm00
    - Lightfield2Channel

test_data:
  names: [platyn1]
  indices: [0-3]
  transforms:
    - norm00
    - Lightfield2Channel
