- Squeeze: {apply_to: [pred, ls_reg]}
- Assert: {apply_to: [pred, ls_reg], expected_tensor_shape: [null, null, null]}
- InsertSingletonDimension: {apply_to: [pred, ls_reg], axis: 0}
- Assert: {apply_to: [pred, ls_reg], expected_tensor_shape: [1, null, null, null]}
- Cast: {apply_to: [pred, ls_reg], dtype: float32, device: cpu}
