- Squeeze: {apply_to: [pred, ls_trf]}
- Assert: {apply_to: [pred, ls_trf], expected_tensor_shape: [null, null, null]}
- InsertSingletonDimension: {apply_to: [pred, ls_trf], axis: 0}
- Assert: {apply_to: [pred, ls_trf], expected_tensor_shape: [1, null, null, null]}
- Cast: {apply_to: [pred, ls_trf], dtype: float32, device: cpu}
