- Squeeze: {apply_to: [pred, ls_slice]}
- Assert: {apply_to: [pred, ls_slice], expected_tensor_shape: [null, null]}
- InsertSingletonDimension: {apply_to: [pred, ls_slice], axis: 0}
- Assert: {apply_to: [pred, ls_slice], expected_tensor_shape: [1, null, null]}
- Cast: {apply_to: [pred, ls_slice], dtype: float32, device: cpu}
