model:
  name: A02
  kwargs:
    affine_transform_classes:
      361,67,77: Heart_tightCrop_Transform
      361,77,67: Heart_tightCrop_Transform
      361,66,77: Heart_tightCrop_Transform
      361,77,66: Heart_tightCrop_Transform
#      361,62,93: staticHeartFOV_Transform
#      361,93,62: staticHeartFOV_Transform
    interpolation_order: 2
    n_res2d: [128, 128, u, 64, 64]
    inplanes_3d: 32
    n_res3d: [[32, 8], [8], [1]]
    final_activation: null
  nnum: 19
  z_out: 49
  precision: float
  checkpoint: /g/kreshuk/beuttenm/repos/lnet/logs/fish/fdyn1_a02/20-02-21_08-54-55/models/v0_model_4.pth


log:
    log_scalars_every: [1, iteration_completed]
    log_images_every: [1, epoch_completed]
    log_bead_precision_recall: false
    save_n_checkpoints: 2

train:
  loss:
    name: WeightedSmoothL1Loss
    kwargs: {threshold: 0.8, initial_weight: .05, apply_below_threshold: true, decay_by: .8, every_nth_epoch: 1}

  optimizer:
    name: Adam
    kwargs: {lr: 4.0e-4, eps: 1.0e-8}

  max_num_epochs: 500
  validate_every_nth_epoch: 1
  score_function: MS-SSIM
  patience: 5

  data:
    batch_size: 1
    transforms:
      - {name: norm01, kwargs: {apply_to: 0, percentile_min: 5.0, percentile_max: 99.8}}
      - {name: norm01, kwargs: {apply_to: 1, percentile_min: 5.0, percentile_max: 99.99}}
      - {name: additive_gaussian_noise, kwargs: {apply_to: 0, sigma: 0.1}}
      - {name: additive_gaussian_noise, kwargs: {apply_to: 1, sigma: 0.05}}
      - {name: RandomIntensityScale, kwargs: {factor_between: [.8, 1.2]}}
#    batch_transforms:
      - RandomRotate
      - RandomFlipXYnotZ
      - Lightfield2Channel

    fish2_20191209_dynamic.t0454c2: {indices: 30-10535, interpolation_order: 2}   # lenght: ‭10,965‬
#    fish2_20191209_dynamic.t0454c3: {indices: 71-170|282-452|, interpolation_order: 2}  # lenght: ‭10,965‬
#    fish2_20191209_dynamic.t0521c2: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0521c3: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p40: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p60: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p80: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p100: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p120: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p140: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p160: {indices: null, interpolation_order: 2}


eval:
  batch_size: 2
  transforms:
    - {name: norm01, kwargs: {apply_to: 0, percentile_min: 5.0, percentile_max: 99.8}}
    - {name: norm01, kwargs: {apply_to: 1, percentile_min: 5.0, percentile_max: 99.99}}
    - Lightfield2Channel

  valid_data:
    fish2_20191209_dynamic.t0454c2: {indices: 10535-10750, interpolation_order: 2}  # lenght: ‭10,965‬

  test_data:
    fish2_20191209_dynamic.t0454c2: {indices: 10750-10965, interpolation_order: 2}  # lenght: ‭10,965‬

#    fish2_20191209_dynamic.t0541c3p30: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p50: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p70: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p90: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p110: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p130: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p150: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c3p170: {indices: null, interpolation_order: 2}


#    fish2_20191209_dynamic.t0541c2p40: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p60: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p80: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p100: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p120: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p140: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p160: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p30: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p50: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p70: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p90: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p110: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p130: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p150: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0541c2p170: {indices: null, interpolation_order: 2}
#
#    fish2_20191209_dynamic.t0402c10p80: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c11p80: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c10p100: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c11p100: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c10p120: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c11p120: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c10p140: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c11p140: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c10p160: {indices: null, interpolation_order: 2}
#    fish2_20191209_dynamic.t0402c11p160: {indices: null, interpolation_order: 2}
